# -*- coding: utf-8 -*-
"""coopresearch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLchnmAL6A9A9qSRVt7znxS6BAJuawxh
"""

pip install graphviz

from graphviz import Digraph

dot = Digraph(comment='Community Detection Framework')

# Top Title
dot.node('A', 'COMMUNITY DETECTION\nRESEARCH FRAMEWORK', shape='box')

# Sections
dot.node('B', 'INPUT DATASETS\n\nReal:\nKarate Club\nDolphins\nLes Miserables\n\nSynthetic:\nLFR Benchmark', shape='box')

dot.node('C', 'ALGORITHMS\n\nLouvain\nSLPA\nBIGCLAM', shape='box')

dot.node('D', 'EVALUATION\n\nAccuracy (NMI)\nScalability\nMemory\nStability', shape='box')

dot.node('E', 'KEY FINDINGS\n\nLouvain: Fast\nSLPA: Balanced\nBIGCLAM: Accurate', shape='box')

dot.node('F', 'GUIDELINES\n\nLarge → Louvain\nOverlaps → SLPA\nAccuracy → BIGCLAM', shape='box')

# Connections
dot.edges(['AB', 'BC', 'CD', 'DE', 'EF'])

# Save and view
dot.render('community_detection_diagram', format='png', view=True)